[package]
name = "ckziu-codefest-api"
authors = ["Tymon Woźniak <tymon.student@gmail.com>"]
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
warp = "0.3.6"
chrono = "0.4.37"
jsonwebtoken = "9.3.0"
serde_json = "1.0.115"
thiserror = "1.0.58"
log = "0.4.21"
env_logger = "0.11.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
