[package]
name = "ckziu-codefest-api"
authors = ["Tymon Woźniak <tymon.student@gmail.com>"]
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3.18"
#sqlx = { version = "0.7.4", features = ["runtime-async-std", "postgres"] }
tide = { version = "0.16.0" }
